## docker compose down && docker compose build && docker compose up -d && docker compose logs
## conf profile PRD
## https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Deployment

services:

  django:
    build:
      context: backend
    hostname: geneappserver
    volumes:
      - ./data:/tmp/geneappdata
    env_file:
      - ./profile_PRD.env

  flask:
    build:
      context: service
    hostname: geneappservice
    volumes:
      - ./data:/tmp/geneappdata
    env_file:
      - ./profile_PRD.env

  nuxt:
    build:
      context: frontend
    hostname: geneappexplorer
    env_file:
      - ./profile_PRD.env

  nginx:
    build:
      context: proxy
    depends_on:
      - django
      - nuxt
      - flask
    ports:
      - 80:8080
    restart: always
    volumes:
      - ./data:/tmp/geneappdata
