# Generated by Django 4.2.7 on 2023-12-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('control', models.CharField(max_length=100)),
                ('treatment', models.CharField(max_length=100)),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
                ('organism', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genome', models.CharField(blank=True, max_length=100, null=True)),
                ('online', models.BooleanField(default=False)),
                ('anotattion', models.CharField(max_length=200)),
                ('proteome', models.CharField(max_length=200)),
                ('transcriptome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('local_path', models.CharField(blank=True, max_length=100, null=True)),
                ('acession', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
